# Generated by Django 3.1.5 on 2021-05-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('summary', models.TextField(verbose_name='Sumário')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.IntegerField()),
                ('avaliability', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=False)),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
    ]
