# Generated by Django 3.1.5 on 2021-05-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-05-13', verbose_name='Criado em'),
            preserve_default=False,
        ),
    ]
